
module.exports = {
    somthingBadHappend: "הפעולה נכשלה",
    permssionDenied: "המשתמש אינו רשאי לבצע את הפעולה",
    userDoesNotExist: "משתמש אינו קיים",
    shiftDoedNotExist: "משמרת לא קיימת",
    storeDoesNotExist: "חנות לא קיימת",
    productDoesNotExist: "מוצר לא קיים",
    passwordIsIncorrect: "סיסמא לא נכונה",
    userIsNotLoggedIn: "המתמש אינו מחובר",
    UsernameOrIdAlreadyExists: "שם משתמש או תעודה זהות קיימים כבר במערכת",
    PasswortToShort: "אורך סיסמא מינימאלי הוא 6 תווים",
    idTooShort: "אורך תעודת זהות מינימאלית הוא 6 תווים",
    incorectEmail: "מייל לא נכון",
    storeAlreadyExist: "החנות קיימת כבר במערכת",
    duplicateStore: "חנות באותו השם ובאותו האזור קיימת כבר במערכת",
    shiftsCurrentTimeError: "לא ניתן להוסיף משמרת לפני התאריך הנוכחי",
    invalidDateRange: "התאריכים שניתנו אינם תקינים",
    userCannotHaveMoreThanOneShiftAtDay: "לדייל לא יכולה להיות יותר ממשמרת אחת ליום",
    shiftTypeEvemt: "אירוע",
    shiftWirhoutSalesmanError:"יש לשבץ לכל משמרת דייל",
    userDoestSalesman: "המשתמש אינו דייל מכירות",
    shiftAlreadyPublished: "המשמרת אותה אתה מנסה לפרסם כבר פורסמה",
    shiftSalesmanDoesntHaveShift: "לדייל אין משמרת היום",
    illegalkmOrParkingCost: "מספר קילומטרים או עלות אינם חוקיים",
    shiftDoesNotPublished: "הממשמרת עדיין לא פורסמה",
    illegalQuantity: "כמות מוצר לא חוקית",
    shiftDoesnotStarted: "המשמרת עדיין לא התחילה",
    shiftAlreadyStarted: "לא ניתן לערוך משמרת שהתחילה",
    shiftCannotBeEdited: "לא ניתן לערוך משמרת זו",
    shiftNotFinished: "לא ניתן לערוך משמרת שאינה הסתיימה",
    productAlreadyExist: "המוצר כבר קיימת",
    productWithTheSameNameAndCategoryAlreadyExist: "לא ניתן להוסיף מוצר עם אותו הקטגוריה ואותו השם",
    productCannotBeEdited: "לא ניתן לערוך את המוצר",
    serverError: "שגיאה התרחשה בשרת. אנסה נסה שוב מאוחר יותר",
    noSuchShiftStatus: 'סוג משמרת זה לא קיים במערכת. אנה נסה שנית',
    shiftsForAgentTitle_string: "שלום רב. להלן המשמרות הקרובות המיועדים לחנויות שלך.",
    date_string: "תאריך",
    hours_string: "שעות",
    city_string: "עיר",
    storeName_string: "שם החנות",
    salesmanName_string: "שם הדייל",
    deleteError: "קרתה תקלה בעת המחיקה",
    eventSalary: 42,
    encCatagoryManager: "תמריץ מנהלת",
    encCatagorywiskey: "קטגוריית וויסקי",
    encCatagoryCampary:  "גרופו קמפרי",
    encCatagoryVodks: "קטגוריית וודקה",
    encCatagoryTavor: "שיווק תבור",
    encCatagoryBerdens: "רזרב ברנדס"
};