add = "//*[@id=\"app\"]/div/div[3]/button"
edit = "//*[@id=\"app\"]/div/div[3]/div[1]/div/button"
delete = "//*[@id=\"app\"]/div/div[3]/div[1]/div/header/h4/a/svg/g/path"

name = "//*[@id=\"app\"]/div/div[3]/form/div[3]/input"
product = "//*[@id=\"app\"]/div/div[3]/form/div[5]/div/select"
subCategory = "//*[@id=\"app\"]/div/div[3]/form/div[7]/div/select"
quantity = "//*[@id=\"app\"]/div/div[3]/form/div[10]/input"
bonus = "//*[@id=\"app\"]/div/div[3]/form/div[12]/input"
addBtn = "//*[@id=\"app\"]/div/div[3]/form/div[13]/button"
