changePass = "//*[@id=\"app\"]/div/div[1]/a[7]"
productsTab = "//*[@id=\"app\"]/div/div[1]/a[2]"
storesTab = "//*[@id=\"app\"]/div/div[1]/a[3]"
usersTab = "//*[@id=\"app\"]/div/div[1]/a[4]"
incentivesTab = "//*[@id=\"app\"]/div/div[1]/a[5]"
ShiftsTab = "//*[@id=\"app\"]/div/div[1]/div[1]/button"
CreateShiftTab = "//*[@id=\"app\"]/div/div[1]/div[1]/div/a[1]"
reportsTab = "//*[@id=\"app\"]/div/div[1]/div[2]/button"
logoutTab = "//*[@id=\"app\"]/div/div[1]/a[6]"
mainTab = "//*[@id=\"app\"]/div/div[1]/a[1]"

