add = "//*[@id=\"app\"]/div/div[3]/div[1]/button[1]"
edit = "//*[@id=\"app\"]/div/div[3]/div[2]/div[2]/div[2]/table/tbody/tr/td[8]/button"
delete = "//*[@id=\"app\"]/div/div[3]/div[2]/div[2]/div[2]/table/tbody/tr/td[9]/button"

store = "//*[@id=\"app\"]/div/div[3]/form/div[3]/select"
username = "//*[@id=\"app\"]/div/div[3]/form/div[5]/select"
type = "//*[@id=\"app\"]/div/div[3]/form/div[7]/select"
date = "//*[@id=\"app\"]/div/div[3]/form/div[9]/input"
startTime = "//*[@id=\"app\"]/div/div[3]/form/div[11]/input"
endTime = "//*[@id=\"app\"]/div/div[3]/form/div[13]/input"
addBtn = "//*[@id=\"app\"]/div/div[3]/form/div[16]/button"
