add = "//*[@id=\"app\"]/div/div[3]/button"
edit = "//*[@id=\"app\"]/div/div[3]/div[1]/div[2]/div[2]/table/tbody/tr[1]/td[8]/button"
delete = "//*[@id=\"app\"]/div/div[3]/div[1]/div[2]/div[2]/table/tbody/tr[1]/td[9]/button"

username = "//*[@id=\"app\"]/div/div[3]/form/div[3]/input"
role = "//*[@id=\"app\"]/div/div[3]/form/div[5]/select"
startDate = "//*[@id=\"app\"]/div/div[3]/form/div[7]/input"
idNum = "//*[@id=\"app\"]/div/div[3]/form/div[10]/div[3]/input"
sex = "//*[@id=\"app\"]/div/div[3]/form/div[10]/div[9]/select"
email = "//*[@id=\"app\"]/div/div[3]/form/div[10]/div[15]/input"
addBtn = "//*[@id=\"app\"]/div/div[3]/form/div[12]/button"
